### ISSUE TITLE
Error on Unity 2022.3.37f1 - EncodeTexture Parameter Issue

### ISSUE THREAD

**Issue by brian-kryptomon** [WalletConnect/Web3ModalUnity#13]
### Link to minimal reproducible example

Simply install on unity version above and project won't start

### Summary

The build will not compile on this unity version because it says the encodetexture method requires int not colors. 

I have downgraded back to 0.3.2 and it works fine so seems like an issue on the latest version only.

### List of related npm package versions

OpenUPM standard config per install instructions:

		"com.nethereum.unity",
		"com.walletconnect.core",
		"com.walletconnect.nethereum",
		"com.walletconnect.ui",
		"com.walletconnect.web3modal"
		
package:
    "com.walletconnect.web3modal": "0.4.0"

**Comment by skibitsky** [comment]
Hey @brian-kryptomon,

Does that happen in one of our sample Unity projects or in your own project?

**Comment by thirdheronet** [comment]
yop i can confirm, 0.4.0 is broken, there is fatal error in the code, you need replace 2 parameters for int (probably size of QR texture), i putted there 256, 256 (or something like that) and its works, but its just emergency solution, i did not want downgrade, i even created new Unity project to verify that..

`Library\PackageCache\com.walletconnect.web3modal\Runtime\Components\QrCode.cs(58,70): error CS1503: Argument 2: cannot convert from 'UnityEngine.Color' to 'int'
`

![Screenshot 2024-07-16 160353](https://github.com/user-attachments/assets/d31d9e49-7f01-435f-8f60-54e4d536df3e)

**Comment by skibitsky** [comment]
Thanks, I'll fix it asap

**Comment by brian-kryptomon** [comment]
Thanks all - btw the implementation on this is very solid. The only thing
I've found a little bit challenging is that the on connect is an event and
it would nice to have something as an async await style call but I
understand why it was done. I got around it by using the
TaskCompletionSource pattern so I'm not blocked.

-Brian

**Comment by skibitsky** [comment]
> it would nice to have something as an async await style call

I can look into adding an async method. What do you expect to happen when you call it? Should a modal open?

**Comment by brian-kryptomon** [comment]
Yeah ideally it would open the modal and return the account or some sort of connected success indicator. -BrianOn Jul 16, 2024, at 12:09 PM, Gleb Skibitsky ***@***.***> wrote:﻿

it would nice to have something as an async await style call

I can look into adding an async method. What do you expect to happen when you call it? Should a modal open?

**Comment by skibitsky** [comment]
@brian-kryptomon @thirdheronet could you please try v0.4.1?

**Comment by thirdheronet** [comment]
@skibitsky for me it's works, the error is done and QR image works too..
