### ISSUE TITLE
**Title:** Issue with WalletConnect Integration in Web3 Unity Application

### ISSUE THREAD

**Issue by Myomin78779** [WalletConnect/Web3ModalUnity#20]
**Comment:**
I'm experiencing difficulties with the integration of WalletConnect in my Web3 Unity application. The issue arises when attempting to connect to the wallet, where the connection either fails or gets stuck in a loading state. I've followed the provided documentation and ensured all necessary dependencies are included. Any assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by skibitsky** [comment]
Hello @Myomin78779,

Could you please open an issue with [Bug Report template](https://github.com/WalletConnect/Web3ModalUnity/issues/new?assignees=&labels=bug&projects=&template=%F0%9F%90%9E-bug-report.md&title=) and provide more details so that I could investigate your issue?
