### ISSUE TITLE
[feature] Wallet Connections on PC Unity Apps

### ISSUE THREAD

**Issue by brian-kryptomon** [WalletConnect/Web3ModalUnity#23]
### What problem does this new feature solve?

The current solution for Unity on PC appears to be that we need to scan the QR code image generated by the web3modal plugin on a mobile phone. This feels cumbersome for a player who is already on PC and likely has their wallet on their browser.

We are looking for a single platform solution to connect a wallet in game to a browser based plugin.

### Describe the solution you'd like

As a player I should be able to choose my wallet and if I am on PC it should give the QR code to scan or give a link that can be copy and pasted into a browser to connect via your browser wallet extension.

I tried to find solutions using the QR code copy link but I can't seem to find it. If this is supported it would be good to have some documentation on how to use this feature.

**Comment by skibitsky** [comment]
Hello,

Thank you for opening the issue!

It's already possible to connect PC wallets. Below is the list of target platforms and connectors they support:

### WebGL
- Browser extensions such as Rabbit, MetaMask, Brave, etc (video clip below)
- QR code
- Deep Linking with local apps such as Ledger Live
- Coinbase Smart Wallet 

### Desktop (Windows, macOS)
- QR code
- Deep Linking with local apps such as Ledger Live

### Mobile
- QR code
- Deep Linking with local apps such as Trust, MetaMask, Rainbow, etc


https://github.com/user-attachments/assets/e54b2050-29ee-4cd1-a45d-cef1efdff96f

**Comment by brian-kryptomon** [comment]
On desktop - can I deep link to a browser metamask app? The main issue is
many people have their wallets on their browser plugins and when they play
our game on desktop they have to have their wallet on their mobile device
if they want to sign. In an ideal world - the desktop sdk would have an
option for folks to open their browser and sign via the metamask browser
plugin.

Is this possible in some way?

**Comment by chris13524** [comment]
MetaMask browser extension does not support WalletConnect unfortunately
