### ISSUE TITLE
[Unity] Doesn't open wallet app on WebApp / WebView (Telegram on mobile phone)

### ISSUE THREAD

**Issue by frostmyr** [WalletConnect/Web3ModalUnity#29]
**Describe the bug**
I deployed my WebGL game, made with Unity, on Telegram (mobile). But after selecting a wallet, for instance metamask, it doesn't redirect me to the metamask app, instead it shows this error (attached below). I have tested opening the game directly on web browser and it does work (opens the metamask app after selecting the wallet).

**To Reproduce**

1. Usual Web3Modal implementation for Unity
2. Build for WebGL platform
3. Deploy to Telegram as WebApp

**Expected behavior**
Opens the wallet app after selecting a wallet

**Screenshots**
![image](https://github.com/user-attachments/assets/f98147c4-2577-4d4a-9055-4048913e2d0e)

**Environment**

- Android: Android 12 (not sure if this matters)
- Unity version: 2022.3.20f1
- Web3Modal Package Version: v0.4.2

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
On mobile telegram only

**Wallets used for testing**
Metamask

**Additional context**
-

**Comment by skibitsky** [comment]
Hello,

Thank you for opening the issue! We are aware of this and working on a solution.

**Comment by frostmyr** [comment]
> Hello,
> 
> Thank you for opening the issue! We are aware of this and working on a solution.

Any estimation on how long this will take to fix?

**Comment by skibitsky** [comment]
Fixed in [Reown AppKit](https://docs.reown.com/appkit/unity/core/installation) v1.1.0
